flowchart TD

init{{"Start"}}
err["Get error message"]
suggest["Match suggestion"]
found{"Got suggestions?"}
success{"Execution successful?"}
exit{{"Exit"}}

init --> err --> suggest --> found -->|Yes, prompt fixes| success -->|Yes| exit

%% subgraph "Main Flow"
%% init
%% err
%% suggest
%% found
%% success
%% exit
%% end

subgraph errsource["Error sources"]
direction TB
from_env["Environment variable"]
from_multiplexer["`Terminal multiplexer
(tmux, GNU Screen, Zellij)`"]
%% subgraph multiplexer["Terminal multiplexers"]
%% direction LR
%% from_tmux["tmux"]
%% from_screen["GNU Screen"]
%% from_zellij["Zellij"]
%% end
from_execution["Last command execution"]
end

from_env --> from_multiplexer --> from_execution

%% from_tmux --- from_screen --- from_zellij

errsource --> err
%% from_env["Enviroment variable"] --> err
%% from_tmux["`tmux`"] --> err
%% from_execution["Last command execution"] --> err

subgraph suggestsource["Suggestion sources"]
direction LR
builtin
module
fallback
end

%% suggestsource --> suggest
builtin["Compiled suggestions"] --> suggest
module["Module suggestions"] --> suggest

%% fallback modules loop
found -->|No| fallback["Fallback modules"]
fallback --> |If no suggestions| exit
fallback --> |If gives suggestions, prompt fixes| success

%% found -->|Yes| success
success -->|No| err
