steps:
  - name: nightly-tag
    image: alpine
    when:
      event: cron
      cron: "nightly build"
    environment:
      GIT_NAME: iff
      GIT_EMAIL: iff@ik.me
      KEY:
        from_secret: Codeberg-CI
    commands:
      - apk add --no-cache git
      - git fetch --tags origin
      - GIT_TAGS=$(git tag --points-at HEAD)
      - |
        if ! echo "$GIT_TAGS" | grep -q "nightly"; then
          echo "Updating nightly tag"

          git tag -f nightly

          apk add --no-cache openssh-client
          mkdir -p ~/.ssh
          echo "$KEY" > ~/.ssh/key
          chmod 600 ~/.ssh/key
          ssh-keyscan codeberg.org >> ~/.ssh/known_hosts
          echo "Host codeberg.org" > ~/.ssh/config
          echo "  IdentityFile ~/.ssh/key" >> ~/.ssh/config

          git config --global user.name "$GIT_NAME"
          git config --global user.email "$GIT_EMAIL"

          git push git@codeberg.org:iff/pay-respects.git tag nightly --force
        fi

