command = "_PR_general"

[[match_err]]
pattern = [
	"command not found",
	"unknown command",
	"nu::shell::external_command",
	"is not recognized as a name of a cmdlet"
]
suggest = [
'''
{{select[0](path)}} {{command[1:]}} ''',
# if command starts with `z `, it's likely using zoxide.
# zoxide defines a function, therefore the output is unobtainable in a non-interactive shell.
'''
#[FUNCTION, cmd_contains(^(z\s+)), min_length(2)]
ZoxideIntegration
'''
]

[[match_err]]
pattern = [
	"permission denied",
	"is not an executable file"
]
suggest = [
'''
#[cmd_contains((?m)^(\S*)\/(\S*))]
chmod +x {{command[0]}} &&
{{command}}'''
]
