command = "_PR_fallback"

[[match_err]]
pattern = [
	"access",
	"permission",
	"permitted",
	"privilege",
	"protected",
	"root",
	"sudo",
	"super-user",
	"superuser",
]
suggest = [
'''
#[FUNCTION]
SetPrivilege
'''
]

[[match_err]]
suggest = [
'''
#[FUNCTION, min_length(2), INLINE]
DesperateFileLookUp
''',
'''
#[FUNCTION, INLINE]
DesperateFuzzyRecovery
''',
]
