command = "brew"

[[match_err]]
pattern = [
	"unknown command"
]
suggest = [
'''
{{command[0]}} {{typo[1](
--cache,
--caskroom,
--cellar,
--env,
--prefix,
--repository,
--version,
alias,
analytics,
audit,
autoremove,
bottle,
bump,
bump-cask-pr,
bump-formula-pr,
bump-revision,
bump-unversioned-casks,
bundle,
casks,
cat,
cleanup,
command,
commands,
completions,
config,
contributions,
create,
debugger,
deps,
desc,
determine-test-runners,
developer,
dispatch-build-bottle,
docs,
doctor,
edit,
extract,
fetch,
formula,
formula-analytics,
formulae,
generate-analytics-api,
generate-cask-api,
generate-cask-ci-matrix,
generate-formula-api,
generate-man-completions,
gist-logs,
help,
home,
info,
install,
install-bundler-gems,
irb,
leaves,
link,
linkage,
list,
livecheck,
log,
migrate,
missing,
nodenv-sync,
options,
outdated,
pin,
postinstall,
pr-automerge,
pr-publish,
pr-pull,
pr-upload,
prof,
pyenv-sync,
rbenv-sync,
readall,
reinstall,
release,
rubocop,
ruby,
rubydoc,
search,
services,
setup-ruby,
sh,
shellenv,
style,
tab,
tap,
tap-info,
tap-new,
test,
tests,
typecheck,
unalias,
unbottled,
uninstall,
unlink,
unpack,
unpin,
untap,
update,
update-if-needed,
update-license-data,
update-maintainers,
update-python-resources,
update-report,
update-reset,
update-sponsors,
update-test,
upgrade,
uses,
vendor-gems,
vendor-install,
verify
)}} {{command[2:]}} '''
]

[[match_err]]
pattern = [
	"this command updates brew itself"
]
suggest = [
'''
{{command[0]}} upgrade {{command[2:]}} '''
]
