command = "jj"

[[match_err]]
pattern = [
	"There is no jj repo in \".\"",
]
suggest = [
'''
{{command[0]}} git init
''',
]

[[match_err]]
pattern = [
	"unrecognized subcommand",
]
suggest = [
'''
#[err_contains('git')]
{{command[0]}} git {{command[2:]}}
''',
'''
#[cmd_contains(\s((push)|(fetch)|(clone)|(init)|(remote))), INLINE]
{{command[0]}} git {{command[1:]}}
''',
'''
#[cmd_contains(\s(pull)), INLINE]
{{command[0]}} git fetch
''',
]

[[match_err]]
pattern = [
	"error: commit",
	"is immutable`",
	"pass `--ignore-immutable`", # deprecated
]
suggest = [
'''
{{command}} --ignore-immutable
''',
]

[[match_err]]
pattern = [
	"no bookmarks found in the default push revset",
]
suggest = [
'''
{{command}} --change @
''',
]

[[match_err]]
pattern = [
	"hint: run",
	"and try again",
]
suggest = [
'''
{{err::Hint: Run `(.*)` and try again.}} &&
{{command}}
''',
'''
{{err::Hint: Run `(.*)` and try again.}}
''',
]

# deprecated
[[match_err]]
pattern = [
	"use --allow-new to push new bookmark"
]
suggest = [
'''
{{command}} --allow-new'''
]
