command = "jj"

[[match_err]]
pattern = [
	"error: commit",
	"is immutable`",
]
suggest = [
'''
{{command}} --ignore-immutable
''',
]

[[match_err]]
pattern = [
	"no bookmarks found in the default push revset",
]
suggest = [
'''
{{command}} --change @
''',
]

[[match_err]]
pattern = [
	"hint: run",
	"and try again",
]
suggest = [
'''
{{err::Hint: Run `(.*)` and try again.}} &&
{{command}}
''',
'''
{{err::Hint: Run `(.*)` and try again.}}
''',
]
