name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Caching
        uses: Swatinem/rust-cache@v2
        with:
          key: build-and-test

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

